### ISSUE TITLE
x3_group 需要合并的简单方法与接口

### ISSUE THREAD

**Issue by haimxu** [CallmeNezha/x3#1]
x3_group 合并时需要 x3_group._group.extend(x3_group._group) 比较麻烦，且行为不清晰

**Comment by CallmeNezha** [comment]
增加了 + 操作符，现在可以做 x3 + x3 -> x3_group , x3_group + x3 -> x3_group , x3_group + x3_group -> x3_group 等操作，请更新 pip install --upgrade pyx3
